version: '3.8'
services:

 database:
   image: database:1.0.0
   ports:
     - "7000:8080"
     - "9000"
   networks:
     - private_network
   deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
     resources:
       limits:
         cpus: '0.50'
         memory: 750M

 web:
   image: app:1.0.0
   ports:
     - "8081:8081"
   networks:
     - private_network
   depends_on:
     - database
   deploy:
     replicas: 4
     restart_policy:
       condition: on-failure
     resources:
       limits:
         cpus: '0.50'
         memory: 750M

networks:
 private_network:
